### ISSUE TITLE
New Google Flights UI?

### ISSUE THREAD

**Issue by m16p** [dbugger/legroom#11]
Where does the legroom info show on the new Google Flights UI?  I don't see it in the search result page anymore :(

**Comment by dbugger** [comment]
The extension has been updated to support new UI months ago. It looks like this:
![capture](https://user-images.githubusercontent.com/258165/41306727-e9368a72-6e2b-11e8-8483-3a1a5bc5e297.PNG)

If you are not seeing it, can you send me the version of the extension installed?

**Comment by m16p** [comment]
Hmmm, yeah, I definitely don't see that.  It says I'm using version 1.8.1, which seems to be the newest version.  Just tried uninstalling the extension and reinstalling it, still doesn't show up.

I'm using Linux, in case that makes a difference?

**Comment by dbugger** [comment]
I tested in on Ubuntu 16.04 and no problem. Works on Windows 10 as well.
Do you mind trying this out? On Chrome address bar, type:
chrome://policy
then press Enter.
Do you see anything under Chrome policies? Do you see an item called IsolateOrigins?

**Comment by m16p** [comment]
Yes, IsolateOrigins is there, and google.com is in that item.  Is that the issue?  Should I remove that?  I've never manually added anything there as far as I know, what does it do, and any idea why it would be there?

Thanks!

**Comment by dbugger** [comment]
If you already cleaned up IsolateOrigins, then the next thing to look at is ExtensionSettings (also under chrome://policy). You should see declaration for '*' (i.e. all) and see if runtime_blocked_hosts contains *.google.com.
However, if you are using a corporate machine/device, it is probably best for you not to change these policies.  This kind of policy is usually setup by your corporate IT, part of Google Chrome Enterprise program. If this is your personal device, then it's all yours.

**Comment by m16p** [comment]
Yes, "*://*.google.com" is in runtime_blocked_hosts as well.  And removing it there makes the legroom extension work :)  But yeah, I don't know if I really should keep that change, since this is a corp device.  If I could *just* change it for Google Flights and not the rest of Google, then I'd do that, but alas that isn't an option :(  If Google Flights had its own subdomain (like "flights.google.com") then I could do it, but not with "google.com/flights".

So I've reverted the changes, and instead I'll just use the Chromium browser when searching on Google Flights, since corp didn't install any policies there so your extension works there :)

Thanks for your help with this!

**Comment by dbugger** [comment]
Thanks for figuring it out! I'll think of other way to embed additional UI without having to inject content into the webpage. Locked down corporate machines might be more common than I had thought.
