### ISSUE TITLE
Flight Pricing Mapping Incorrect

### ISSUE THREAD

**Issue by ming94539** [dbugger/legroom#16]
<img width="531" alt="Screen Shot 2022-10-22 at 11 43 15 PM" src="https://user-images.githubusercontent.com/29558829/197374218-246d24d6-184f-437e-9111-91e2c7f59c89.png">

We noticed that the mapping for `processItinerary` is incorrect for pricing.
See screenshot for correction.

;)

**Comment by dbugger** [comment]
Nice, good catch!
The extension currently doesn't use the pricing data. I do not remember why I even bother referencing it.
Curious, why are you digging into it?

**Comment by dbugger** [comment]
Fixed.
