### ISSUE TITLE
Display Issue - Text Wrapping

### ISSUE THREAD

**Issue by infdaze** [dbugger/legroom#17]
<img width="1116" alt="image" src="https://github.com/dbugger/legroom/assets/5102856/67719bf4-c095-4362-be90-6b339725c090">
Something happed that broke the formatting of Legrooms

**Comment by dbugger** [comment]
Thanks for the heads up.

Just sent an update for review to Chrome Web Store, hopefully the approval will come quick.

Thanks again.

**Comment by dbugger** [comment]
Fixed in version 1.9.7.
